name: Build Docker Image

on:
  push:
    branches: main
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      no-cache:
        description: Disable build cache
        required: false
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Image tag
        id: image-tag
        run: |
          tag=latest

          case ${{ github.event_name }} in
            'workflow_dispatch')
              tag=$( echo ${{ github.ref_name }} | head -c 15 )-$( echo ${{ github.sha }} | head -c 7 )
              ;;
            'release')
              tag=${{ github.ref_name }}
              ;;
          esac

          echo "tag=${tag}" >> "$GITHUB_OUTPUT"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/vigilant:${{ steps.image-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: ${{ github.event.inputs.no-cache || false }}
